<?php
require_once('../lib-common.php');
print COM_siteHeader();
?>
<p>Vampire View Sheet </p>
<TABLE WIDTH="572" BORDER="0" CELLPADDING="1" CELLSPACING="0">
<TR>
<TD BACKGROUND="Bg.JPG"><TABLE BORDER="0" CELLPADDING="2" CELLSPACING="1" WIDTH="570" BACKGROUND="nil.GIF">
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Name</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Character Name)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Clan</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Clan Name)</FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Alliegance</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Sabbat/Camarilla/Other)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2"> Nature</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Nature)</FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Generation</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">( ) Gen.</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Demeanor</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Demeanor)</FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Age</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1"> Apparent: ( ) True: ( )</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Concept</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Concept)</FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="TOP" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2"> Description</FONT></B></TD>
<TD VALIGN="TOP" ALIGN="LEFT" COLSPAN="5"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Physical Description)</FONT></TD>
</TR>
<TR>
<TD VALIGN="TOP" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2"> Appearance</FONT></B></TD>
<TD VALIGN="TOP" ALIGN="LEFT" COLSPAN="5"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(General Appearance, clothing style, etc.)</FONT></TD>
</TR>
<TR>
<TD VALIGN="TOP" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Background</FONT></B></TD>
<TD VALIGN="TOP" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Family Status, Social Roots)</FONT></TD>
<TD VALIGN="TOP" ALIGN="LEFT" WIDTH="100"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Birthplace</FONT></B></TD>
<TD VALIGN="TOP" ALIGN="LEFT" COLSPAN="2"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Birthplace)</FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Attributes</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Strength</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Charisma</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Perception</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Dexterity</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Manipulation</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Intelligence</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Stamina</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Appearance</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Wits</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Abilities</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Alertness</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Animal Ken</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Academics</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Athletics</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Crafts</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Computer</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Brawl</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Drive</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Finance</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Dodge</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Etiquette</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Investigation</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Empathy</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Firearms</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Law</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Expression</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Melee</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Linguistics</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Intimidation</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Performance</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Medicine</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Leadership</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Security</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Occult</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Streetwise</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Stealth</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Politics</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Subterfuge</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Survival</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Science</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Specialties</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Specialty)</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Advantages</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Disciplines</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Backgrounds</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Advantages</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Clan Disc.)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Background)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Conscience</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Clan Disc.)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Background)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Conviction</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Clan Disc.)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Background)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Self Control</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Other Disc.)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Background)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Instincts</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Other Disc.)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="80"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Background)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="90"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Courage</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="LEFT" WIDTH="100"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="4"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="2">Merits/Flaws</FONT></B></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Humanity/Path</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="3"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Merits/Flaw)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0"
VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="3"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Merits/Flaw)</FONT></TD>
<TD VALIGN="TOP" ALIGN="CENTER"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Willpower</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="3"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Merits/Flaw)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0"
VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="3"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Merits/Flaw)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><B><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Blood Pool</FONT></B></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="LEFT" COLSPAN="3"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">(Merits/Flaw)</FONT></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="2"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0"
VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/dot.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10"
HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"><IMG SRC="grafix/blank.GIF" WIDTH="10" HEIGHT="10" BORDER="0" HSPACE="0" VSPACE="0"></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD COLSPAN="6" ALIGN="RIGHT" VALIGN="MIDDLE"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">Stat Sheet Generated by : <A HREF="http://sanguinus.com/" TARGET="_blank" STYLE="text-decoration: none"><B>Sanguinus Curae</B></A></FONT></TD>
</TR>
<TR>
<TD VALIGN="MIDDLE" ALIGN="CENTER" COLSPAN="6"><IMG SRC="grafix/nil.GIF" WIDTH="5" HEIGHT="5" BORDER="0"></TD>
</TR>
<TR>
<TD COLSPAN="6" ALIGN="RIGHT" VALIGN="MIDDLE"><FONT FACE="Verdana, Arial, Helvetica" SIZE="1">format and keywords - <A HREF="http://www.white-wolf.com/legalize.html" TARGET="_blank" STYLE="text-decoration: none">&copy;1999 <B>White Wolf Publishing Inc.</B>All Rights Reserved</A></FONT></TD>
</TR>
</TABLE>
</TD>
</TR>
</TABLE>
<?php
print COM_siteFooter();
?>
